name: Build CI

on: [push, pull_request]

jobs:
  build-trusty:

    runs-on: ubuntu-latest
    container: ubuntu:14.04
    steps:
    - name: setup os 
      run: apt-get update && DEBIAN_FRONTEND=noninteractive TZ=Europe/Paris apt-get -y install wget libz-dev libphp5-embed php5-dev autoconf automake gcc make libpcre3-dev libbz2-dev libbz2-dev libxml2-dev libkrb5-dev libdb5.3-dev git
    - name: git checkout
      run: |
        git version
        pwd
        cd ${RUNNER_WORKSPACE}
        env 
        rm -rf $(basename ${GITHUB_REPOSITORY})
        git clone ${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}.git 
        cd $(basename ${GITHUB_REPOSITORY}) 
        git reset --hard ${GITHUB_SHA}
    - name: patch php 
      run: sed -ie "s#uint _res:31#uint res:31#" /usr/include/php5/main/php_output.h
    - name: zabbix source install and configure
      run: |
        find /usr/lib /lib -name "libphp*so*"
        cat /etc/*release
        rm -f zabbix*
        wget --content-disposition "https://cdn.zabbix.com/zabbix/sources/oldstable/4.0/zabbix-4.0.50.tar.gz"; 
        tar xzvf zabbix*.tar.gz
        cd zabbix*/
        ./configure
        cd -
        ./bootstrap.sh
    - name: zabbix module configure
      run: |
        cd zabbix*/
        export ZABBIX_PATH=$PWD
        cd -
        CFLAGS="-w" PATH=/usr/bin:$PATH ./configure \
                          --prefix=$PWD/test \
                          --with-php=/usr  \
                          --with-zabbix-include=$ZABBIX_PATH/include  || (cat config.log;exit 1)
        cat zbx_php_config.h
    - name: zabbix module make
      run: make

  build-focal:

    runs-on: ubuntu-latest
    container: ubuntu:20.04

    steps:
    - uses: actions/checkout@v4
    - name: setup os 
      run: apt-get update && DEBIAN_FRONTEND=noninteractive TZ=Europe/Paris  apt-get -y install libz-dev wget libphp-embed php-dev autoconf automake gcc make libpcre3-dev libbz2-dev libbz2-dev libxml2-dev libkrb5-dev libargon2-dev libargon2-1 libargon2-0 libsodium-dev
    - name: zabbix source install and configure
      run: |
        find /usr/lib /lib -name "libphp*so*"
        cat /etc/*release
        rm -f zabbix*
        wget --content-disposition "https://cdn.zabbix.com/zabbix/sources/stable/5.0/zabbix-5.0.44.tar.gz"; 
        tar xzvf zabbix*.tar.gz
        cd zabbix*/
        ./configure
        cd -
        ./bootstrap.sh
    - name: zabbix module configure
      run: |
        cd zabbix*/
        export ZABBIX_PATH=$PWD
        cd -
        PATH=/usr/bin:$PATH ./configure \
                        --prefix=$PWD/test \
                        --with-php=/usr  \
                        --with-zabbix-include=$ZABBIX_PATH/include  || (cat config.log;exit 1)
        cat zbx_php_config.h
    - name: zabbix module make
      run: make

  build-noble:

    runs-on: ubuntu-latest
    container: ubuntu:24.04

    steps:
    - uses: actions/checkout@v4
    - name: setup os 
      run: | 
        apt-get update && DEBIAN_FRONTEND=noninteractive TZ=Europe/Paris apt-get install -y software-properties-common
        add-apt-repository ppa:ondrej/php
        DEBIAN_FRONTEND=noninteractive TZ=Europe/Paris  apt-get -y install libz-dev wget \
                                           libphp7.4-embed php7.4-dev autoconf automake gcc make \
                                           libpcre3-dev libbz2-dev libbz2-dev libxml2-dev libkrb5-dev libargon2-dev libargon2-1 libsodium-dev
    - name: zabbix source install and configure
      run: |
        set -x
        find /usr/lib /lib -name "libphp*so*"
        cat /etc/*release
        rm -f zabbix*
        # wget --content-disposition "https://cdn.zabbix.com/zabbix/sources/stable/5.0/zabbix-5.0.44.tar.gz" 
        # wget --content-disposition "https://cdn.zabbix.com/zabbix/sources/stable/6.0/zabbix-6.0.35.tar.gz"
        wget --content-disposition "https://cdn.zabbix.com/zabbix/sources/stable/7.0/zabbix-7.0.5.tar.gz"
        tar xzvf zabbix*.tar.gz
        cd zabbix*/
        ./configure
        cd -
        ./bootstrap.sh
    - name: zabbix module configure
      run: |
        cd zabbix*/
        export ZABBIX_PATH=$PWD
        cd -
        PATH=/usr/bin:$PATH ./configure \
                        --prefix=$PWD/test \
                        --with-php=/usr  \
                        --with-zabbix-include=$ZABBIX_PATH/include  || (cat config.log; exit 1)
        cat zbx_php_config.h
    - name: zabbix module make
      run: make