name: Build CI

on: [push, pull_request]

jobs:
  build-trusty:

    runs-on: ubuntu-latest
    container: ubuntu:14.04
    steps:
    - name: setup os 
      run: apt-get update && DEBIAN_FRONTEND=noninteractive TZ=Europe/Paris apt-get -y install wget libz-dev libphp5-embed php5-dev autoconf automake gcc make libpcre3-dev libbz2-dev libbz2-dev libxml2-dev libkrb5-dev libdb5.3-dev git
    - name: git checkout
      run: |
        git version
        pwd
        env 
        rm -rf $(basename ${GITHUB_REPOSITORY})
        git clone ${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}.git 
        cd $(basename ${GITHUB_REPOSITORY}) 
        git reset --hard ${GITHUB_SHA}
    - name: patch php 
      run: sed -ie "s#uint _res:31#uint res:31#" /usr/include/php5/main/php_output.h
    - name: zabbix source install and configure
      run: |
        cd $(basename ${GITHUB_REPOSITORY})
        find /usr/lib /lib -name "libphp*so*"
        cat /etc/*release
        rm -f zabbix*
        wget --content-disposition "https://cdn.zabbix.com/zabbix/sources/oldstable/4.0/zabbix-4.0.50.tar.gz"; 
        tar xzvf zabbix*.tar.gz
        cd zabbix*/
        ./configure
        cd -
        ./bootstrap.sh
    - name: zabbix module configure
      run: |
        cd $(basename ${GITHUB_REPOSITORY})
        cd zabbix*/
        export ZABBIX_PATH=$PWD
        cd -
        CFLAGS="-w" PATH=/usr/bin:$PATH ./configure \
                          --prefix=$PWD/test \
                          --with-php=/usr  \
                          --with-zabbix-include=$ZABBIX_PATH/include  || (cat config.log;exit 1)
    - name: zabbix module make
      run: make

  build-focal:

    runs-on: ubuntu-latest
    container: ubuntu:20.04

    steps:
    - uses: actions/checkout@v4
    - name: setup os 
      run: apt-get update && DEBIAN_FRONTEND=noninteractive TZ=Europe/Paris  apt-get -y install libz-dev wget libphp-embed php-dev autoconf automake gcc make libpcre3-dev libbz2-dev libbz2-dev libxml2-dev libkrb5-dev libargon2-dev libargon2-1 libargon2-0 libsodium-dev
    - name: zabbix source install and configure
      run: |
        find /usr/lib /lib -name "libphp*so*"
        cat /etc/*release
        rm -f zabbix*
        wget --content-disposition "https://cdn.zabbix.com/zabbix/sources/stable/5.0/zabbix-5.0.44.tar.gz"; 
        tar xzvf zabbix*.tar.gz
        cd zabbix*/
        ./configure
        cd -
        ./bootstrap.sh
    - name: zabbix module configure
      run: |
        cd zabbix*/
        export ZABBIX_PATH=$PWD
        cd -
        PATH=/usr/bin:$PATH ./configure \
                        --prefix=$PWD/test \
                        --with-php=/usr  \
                        --with-zabbix-include=$ZABBIX_PATH/include  || (cat config.log;exit 1)
    - name: zabbix module make
      run: make
